--- Makefile.orig	2015-07-20 22:38:16.000000000 -0700
+++ Makefile	2015-07-21 12:21:44.000000000 -0700
@@ -19,7 +19,7 @@
 
 PKGCONFIG_OVERRIDE=	dbus-1.pc.in
 
-BUILD_DEFS+=		VARBASE
+BUILD_DEFS+=		VARBASE DBUS_USER DBUS_GROUP DBUS_SYSTEM_PID_FILE
 
 OWN_DIRS_PERMS+=	${VARBASE}/db/dbus ${DBUS_USER} ${DBUS_GROUP} 0755
 SPECIAL_PERMS+=		libexec/dbus-daemon-launch-helper ${REAL_ROOT_USER} ${DBUS_GROUP} 4511
@@ -34,21 +34,19 @@
 CONFIGURE_ARGS+=	--localstatedir=${VARBASE:Q}
 CONFIGURE_ARGS+=	--sysconfdir=${PKG_SYSCONFDIR:Q}
 
-CONFIGURE_ARGS_GROUPS=	enable disable with without
-
-.if ${OPSYS} == "Darwin"
+.if ${OPSYS} == "Darwin" || ${OPSYS} == "DragonFly" || ${OPSYS} == "FreeBSD"
 # Prevent the configure script from picking up a per-user tmp
 # directory. See the commit message on revision 1.35
-CONFIGURE_ARGS.with+=	session-socket-dir=/tmp
+CONFIGURE_ARGS+=	--with-session-socket-dir=/tmp
 .endif
 
-CONFIGURE_ARGS.Linux=	abstract-sockets selinux
+CONFIGURE_ARGS+=	--without-init-scripts
+CONFIGURE_ARGS+=	--disable-ansi
+CONFIGURE_ARGS+=	--disable-console-owner-file
+CONFIGURE_ARGS+=	--disable-doxygen-docs
+CONFIGURE_ARGS+=	--enable-checks
+CONFIGURE_ARGS+=	--enable-static
 
-CONFIGURE_ARGS.without+=	init-scripts
-CONFIGURE_ARGS.disable+=	ansi
-CONFIGURE_ARGS.disable+=	console-owner-file
-CONFIGURE_ARGS.disable+=	doxygen-docs
-CONFIGURE_ARGS.enable+=		checks static
 ###
 ### XXX the spawn test hangs, and some of these tests may be bogus
 ###
@@ -57,27 +55,21 @@
 #TEST_TARGET=			check
 #.endif
 
-CONFIGURE_ARGS.with+=	dbus-user=${DBUS_USER}
-CONFIGURE_ARGS.with+=	test-socket-dir=${WRKDIR:Q}
+CONFIGURE_ARGS+=	--with-dbus-user=${DBUS_USER}
+CONFIGURE_ARGS+=	--with-test-socket-dir=${WRKDIR:Q}
+CONFIGURE_ARGS+=	--with-system-pid-file=${VARBASE}/run/dbus/${DBUS_SYSTEM_PID_FILE}
 
 PTHREAD_AUTO_VARS=	yes
 
 .if ${OPSYS} == "Linux"
 PLIST.linux=		yes
 .else
-CONFIGURE_ARGS.disable+=\
-			${CONFIGURE_ARGS.Linux}
+CONFIGURE_ARGS+=	--disable-abstract-sockets
+CONFIGURE_ARGS+=	--disable-selinux
 .endif
 
 PLIST_VARS+=    	linux launchd
 
-CONFIGURE_ARGS+=\
-	${CONFIGURE_ARGS_GROUPS:@.g.@			\
-		${CONFIGURE_ARGS.${.g.}:@.a.@		\
-			--${.g.}-${.a.}			\
-		@}					\
-	@:M*}
-
 MAKE_DIRS=		${PKG_SYSCONFDIR}/dbus-1/event.d
 MAKE_DIRS+=		${PKG_SYSCONFDIR}/dbus-1/system.d
 MAKE_DIRS+=		${PKG_SYSCONFDIR}/dbus-1/session.d
@@ -94,10 +86,14 @@
 PKG_GROUPS=		${DBUS_GROUP}
 PKG_USERS=		${DBUS_USER}:${DBUS_GROUP}
 PKG_GECOS.${DBUS_USER}=	System message bus
-PKG_HOME.${DBUS_USER}=	${VARBASE}/run/dbus
+# Modern dbus does not need a home directory for its user
+# PKG_HOME.${DBUS_USER}=	${VARBASE}/run/dbus
+
+USERGROUP_PHASE=	configure
 
-FILES_SUBST+=		DBUS_USER=${DBUS_USER}
-FILES_SUBST+=		DBUS_GROUP=${DBUS_GROUP}
+FILES_SUBST+=		DBUS_USER_SH=${DBUS_USER}
+FILES_SUBST+=		DBUS_GROUP_SH=${DBUS_GROUP}
+FILES_SUBST+=		DBUS_SYSTEM_PID_FILE_SH=${DBUS_SYSTEM_PID_FILE}
 
 BUILDLINK_TRANSFORM+=	rm:-Wl,--gc-sections
 # Package tries to use these if gcc accepts them, but that doesn't
